### ISSUE TITLE
Senstivity analysis by dual numbers at timepoints other than the endpoint 

### ISSUE THREAD

**Issue by ArnoJL** [JuliaDiffEq/DiffEqSensitivity.jl#24] opened 2018-09-16 00:57 UTC
In the documentation there are a few examples where the parameter sensitivity of an ODE by dual numbers is compared to other methods, such as local sensitivity analysis or using Calculus.jl. But this sensitivity analysis is only done at the end point of the simulation. When calculating sensitivities at other time points these methods don't line up for me. 

Comparing sensitivity of the first state to the first parameter by forward differentiation and local sensitivity analysis: 
```
using ForwardDiff
using ForwardDiff: Partials, Dual
using DifferentialEquations
using Plots
using Calculus

#forward differentiation
function func(du,u,p,t)
  du[1] = p[1] * u[1] - p[2] * u[1]*u[2]
  du[2] = -3 * u[2] + u[1]*u[2]
end
p1 = 1.5
p2 = 1.0
u0 = [1.0, 1.0]
tspan = (0.0, 10.0)
p = [p1, p2]

p1dual = Dual{Float64}(p1, (1.0, 0.0))
p2dual = Dual{Float64}(p2, (0.0, 1.0))
pdual = [p1dual, p2dual]
prob_dual = ODEProblem(func,eltype(pdual).(u0),eltype(pdual).(tspan),pdual)
sol_dual = solve(prob_dual,Tsit5(),reltol = 1e-15)

timepoints = [i.value for i in sol_dual.t]
sensitivity_forward_diff = [i[1].partials.values[1] for i in sol_dual.u]
plot(timepoints,sensitivity_forward_diff)

# sensitivity ODE
f_ode_sen = @ode_def_nohes test_sensitivity begin
  du1 = p1 * u1 - p2 * u1*u2
  du2 = -3 * u2 + u1*u2
end p1 p2

prob_ode_sen = ODELocalSensitivityProblem(f_ode_sen,u0,tspan,p)
sol_ode_state_and_sen = solve(prob_ode_sen,Tsit5(),reltol = 1e-9)

timepoints2 = [i for i in sol_ode_state_and_sen.t]
sensitivity_ode_sol = [i[3] for i in sol_ode_state_and_sen.u]
state_ode_sol = [i[3] for i in sol_ode_state_and_sen.u]
plot!(timepoints2,sensitivity_ode_sol)
```
I'm not sure I did everything right, but the way the solution by dual numbers snaps to the correct position only at the end seems odd to me.

**Comment by ChrisRackauckas** [comment] 2018-09-22 17:42
Oddly enough, using `saveat` for interpolated values is perfectly fine.

```julia
sol_dual = solve(prob_dual,Tsit5(),saveat=0.0:0.1:10.0,reltol = 1e-15)
```

fixes it. Hmm

**Comment by ChrisRackauckas** [comment] 2018-09-22 20:53
```julia
sol_dual = solve(prob_dual,Tsit5(),saveat=0.0:0.1:10.0, adaptive = false, dt = 0.1, reltol = 1e-15)
sol_dual2 = DiffEqBase.__solve(prob_dual,Tsit5(),dt = 0.1, adaptive = false, reltol = 1e-15))
```

is fine, so the issue is that the adaptivity algorithm shouldn't propogate a dual.

**Comment by ChrisRackauckas** [comment] 2018-09-22 22:16
Fixed by https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/156

**Closed by ChrisRackauckas** 2018-09-22 22:16 UTC
